-- PostgreSQL schema

CREATE TABLE IF NOT EXISTS OMS_USER (
    user_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    user_url VARCHAR(500) NOT NULL,
    user_type VARCHAR(2),
    user_password VARCHAR(200) NOT NULL,
    use_yn CHAR(1) DEFAULT 'Y',
    insert_dts TIMESTAMP,
    insert_id VARCHAR(100),
    update_dts TIMESTAMP,
    update_id VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS TEST_SUBMIT_LOG (
    msg_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject VARCHAR(200),
    message VARCHAR(2000),
    msg_type INT,
    status INT,
    schedule_time VARCHAR(14),
    submit_time VARCHAR(14),
    callback_num VARCHAR(30),
    rcpt_data VARCHAR(200),
    result VARCHAR(50),
    result_desc VARCHAR(500),
    external_message_id VARCHAR(100),
    requested_at VARCHAR(14),
    sent_at VARCHAR(14),
    error_code VARCHAR(20),
    retry_count INT
);
